services:
  web:
    image: nginx:alpine
    container_name: web
    networks:
      - labnet
    ports:
      - "8080:80"

  api:
    image: python:3.11-slim
    container_name: api
    command: sleep infinity
    networks:
      - labnet

  db:
    image: python:3.11-slim
    container_name: db
    command: sleep infinity
    networks:
      - labnet

  admin:
    image: python:3.11-slim
    container_name: admin
    command: sleep infinity
    networks:
      - labnet

  neo4j:
    image: neo4j:5
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/swarmsecpass
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - labnet

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - labnet

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - labnet

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "container:web"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - suricata_rules:/etc/suricata/rules
      - ./suricata/rules/local.rules:/etc/suricata/rules/local.rules
      - ./suricata/logs:/var/log/suricata
    command: >
      -i eth0
      --set default-rule-path=/etc/suricata/rules
      --set rule-files.0=suricata.rules
      --set rule-files.1=local.rules
    depends_on:
      - web

networks:
  labnet:
    driver: bridge

volumes:
  suricata_rules:
